chore(backend): add lint stage package
Add lint stage package to ensure that only files on git stage will be on lint and prettier fixes

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,7 @@
 echo 'Formarting code on Backend'
-npm run format || (echo 'Prettier on Backend Failed' && exit 1)
-echo 'Checking Lint for Backend'
-npm run lint || (echo 'Lint on Backend Failed' && exit 1)
+npx lint-staged || (echo 'Prettier on Backend Failed' && exit 1)
+echo 'Running Unit and Functionals Tests'
+npm run test || (echo 'Tests on Backend Failed' && exit 1)
+echo 'Running e2e Tests'
+npm run test:e2e || (echo 'E2E Tests on Backend Failed' && exit 1)
 echo 'Lint and Format Finished'
